"""new fields in users model

Revision ID: 655c1acc9513
Revises: ce05881bdd1c
Create Date: 2021-09-28 17:32:07.300929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655c1acc9513'
down_revision = 'ce05881bdd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
